#!/bin/bash
curDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) 		 
sudo /bin/launchctl unload -w /System/Library/LaunchDaemons/bootps.plist 
sudo cp "$curDir/bootpd.plist" /etc/bootpd.plist			 
sudo networksetup -setv6off "Thunderbolt Ethernet"
sudo networksetup -setmanual "Thunderbolt Ethernet" 10.0.0.1 255.255.255.0 10.0.0.1
#sudo ipconfig set en5 MANUAL 10.0.0.1 255.255.255.0
#sudo ifconfig en5 10.0.0.1
sudo /bin/launchctl load -w /System/Library/LaunchDaemons/bootps.plist 

